[project]
name = "y0rfa1se-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-document-dates>=3.6.0",
    "mkdocs-material[recommended]>=9.7.1",
    "pymdown-extensions>=10.20.1",
]
